sudo: required
language: java
os: osx
osx_image: xcode9.3
jdk: oraclejdk8

install: |
  ls -a -l
  ./setup.sh --all
  cd UNDERSEA/libraries/MATLAB/v95/bin/maci64
  find -L . -name . -o -type d -prune -o -type l -exec rm {} +
  cd ../../../../..
  echo "export PATH=$PATH:/Users/travis/build/SirCipher/UNDERSEA/libraries/moos-ivp/bin/"
  cd undersea-agent

script: 
  - ./gradlew build test --scan -s

