sudo: required
language: java
os: osx
osx_image: xcode9.3
jdk: oraclejdk8

# env:
#   - DB=postgres
#   - SH=bash
#   - PACKAGE_VERSION="1.0.*"

install: |
  - ls -a -l
  - setup.sh --all
  - cd libraries/MATLAB/v95/bin/maci64
  - find -L . -name . -o -type d -prune -o -type l -exec rm {} +
  - ./gradlew build test --scan


