/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.type2labs.undersea;


import org.junit.Test;

public class LibraryTest {

    @Test
    public void echoPath() {
        System.out.println(System.getenv("PATH"));
    }
}
