/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.type2labs.undersea.utils;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {

    }
}
