package com.type2labs.undersea.common.missions.planner.model;

import com.type2labs.undersea.common.missions.task.model.Task;

import java.util.List;

/**
 * Structure for a mission that has been generated by a {@link MissionPlanner}. This structure contains all of the
 * sub-missions for agents with the cluster.
 */
public interface GeneratedMission {

    /**
     * Adds an {@link AgentMission} to the structure
     *
     * @param agentMission to add
     */
    void addAgentMission(AgentMission agentMission);

    /**
     * Returns the overall progress that the agents have made through the mission. The progress returned will be the
     * given progress from the last heartbeat from the agents
     *
     * @return the overall progress
     */
    double progress();

    /**
     * Returns the individual {@link AgentMission}s for this generated mission
     *
     * @return the missions
     */
    List<AgentMission> subMissions();

    List<Task> allTasks();

    double[][] polygon();

}
